FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/techiesapp-d65c6/firestore/indexes?create_composite=ClVwcm9qZWN0cy90ZWNoaWVzYXBwLWQ2NWM2L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9yZW50SW52b2ljZXMvaW5kZXhlcy9fEAEaDwoLaW52b2ljZURhdGUQAhoRCg1pbnZvaWNlTnVtYmVyEAIaDAoIX19uYW1lX18QAg